---
title: "Citations"
author: "Toufic Mayassi"
date: "September 15, 2015"
output: 
    html_document:
        toc: true
        number_sections: true
        theme: cosmo
        highight: tango
        fig_width: 8
        fig_height: 8
        fig_caption: yes
        self_contained: false
---

# load the data

```{r, echo=FALSE}
counts_raw <- read.delim("data//counts-raw.txt.gz")
counts_norm <- read.delim("data//counts-norm.txt.gz")
```

# Data exploration 

What's the distribution of authors in all articles of our data set?

```{r, echo=FALSE, author_histogram, fig.cap="Figure 1: Bitches be trippin"}
hist(counts_raw$authorsCount, main="Bitches", xlab="hos")
```

# Facebook Data

How popular are articles on Facebook?

```{r, echo=FALSE, fig.cap= "Figure 1: Bitches be trippin on Facebook"}
hist(log(counts_raw$facebookShareCount), main="Social Media Bitches", xlab="like for a ho")
```

The average number of Facebook shares per paper in the data set is `r mean(counts_raw$facebookShareCount)`