---
title: "dplyr and ggplots"
author: "Toufic Mayassi"
date: "September 15, 2015"
output: html_document
---

# load the data

```{r}
counts_raw <- read.delim("data//counts-raw.txt.gz")
counts_norm <- read.delim("data//counts-norm.txt.gz")
```

#dplyr

```{r}
library("dplyr")
```



```{r}
research <- filter(counts_raw, articleType == "Research Article")
```

```{r}
research_2006 <- filter(research, year == 2006)
nrow(research_2006)
```
```{r}
research_2006_fb <- filter(research, year == 2006, 
                            facebookCommentCount > 0)
nrow(research_2006_fb)
```
```{r}
research_2006_fb_tweet_disease <- filter(research, year == 2006, 
                            facebookCommentCount > 0 | backtweetsCount > 0,
                            grepl("Infectious Diseases", plosSubjectTags))
nrow(research_2006_fb_tweet_disease)
```

# Challenge - Subsetting with dplyr using filter and select

```{r}
low_cite <- select(filter(research, year <= 2008,
                   pdfDownloadsCount > 1000,
                   mendeleyReadersCount > 15,
                   wosCountThru2011 < 10), journal, title, year)
low_cite
```
# using pipes %>% challenge

```{r}
research %>% arrange(desc(wosCountThru2011)) %>% select(title) %>% slice(1:3)
```

```{r}
research %>% arrange(desc(authorsCount)) %>% select(authorsCount, title, journal, plosSubjectTags) %>% slice(1:3)
```

# summarizing with dplyr challenge

```{r}
tweets_per_journal <- research %>% group_by(journal) %>%
  summarize(num =n(),
            mean = mean(backtweetsCount),
            sem = sd(backtweetsCount) / sqrt(num))
tweets_per_journal
```

